update theming

diff --git a/.local/bin/wallpaper b/.local/bin/wallpaper
--- a/.local/bin/wallpaper
+++ b/.local/bin/wallpaper
@@ -1,85 +1,23 @@
-#! /bin/bash
+#!/usr/bin/env bash
 
-# This script is used to set the wallpaper on my desktop.
-# currently it is setup to work on Hyprland but can be easily modified
-# to work on other WMs
 
-if [ -z "$WALLPAPER_DIR" ]; then
-    WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
+script="$HOME/.config/ags/scripts/color_generation/switchwall.sh"
+
+img_path=$(realpath "$1")
+
+if [ -z "$img_path" ]; then
+	echo "No image path provided"
+	exit 1
 fi
 
-if [ -z "$SWWW_CUBIC_BEZIER" ]; then
-    SWWW_CUBIC_BEZIER="0.285,0.885,0.320,1.275"
+if [ ! -f "$img_path" ]; then
+	echo "File not found: $img_path"
+	exit 1
 fi
 
-
-if [ -z "$1" ]; then
-
-    # get all files in WALLPAPER_DIR including subfolders
-    files=("$WALLPAPER_DIR"/**/*)
-    files=("${files[@]##@(jpg|jpeg|png|gif|webp|mp4|mkv|webm)}")
-    file=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")
-else
-	if [ "$1" = "--restore" ]; then
-		file=$(/usr/bin/cat $HOME/.config/wallpaper)
-	else
-		file="$(realpath $1)"
-	fi
+if [ ! -x "$script" ]; then
+	echo "Script not found or not executable: $script"
+	exit 1
 fi
 
-touch $HOME/.config/wallpaper
-echo $file > $HOME/.config/wallpaper
-
-
-if [ -z "$2" ]; then
-    resize_mode="crop"
-else
-    resize_mode="$2"
-fi
-
-screen_x="1920"
-screen_y="1080"
-
-if ( "$XDG_SESSION_DESKTOP" = "Hyprland" ); then
-	screen_x=$(hyprctl -j monitors | jq '.[0].width')
-	screen_y=$(hyprctl -j monitors | jq '.[0].height')
-fi
-
-
-
-transition_pos="$screen_x , $screen_y"
-
-session="$XDG_SESSION_TYPE"
-
-
-
-if [ ! -z "$(pidof mpvpaper)" ]; then
-	killall mpvpaper
-fi
-
-
-if [[ "$file" == *".mp4" ]] || [[ "$file" == *".mkv" ]] || [[ "$file" == *".webm" ]] || [[ "$file" == *".gif" ]] ; then
-	mpvpaper -o "--no-audio --loop --no-config" "*" "$file" & disown
-else
-	if [ $session = "wayland" ]; then
-		if [ -z "$(pidof swww-daemon)" ]; then
-			swww-daemon & disown
-		fi
-		swww img $file --transition-angle=30 --transition-duration=1.5 --transition-fps=144 --transition-bezier="$SWWW_CUBIC_BEZIER" --transition-type=outer --transition-pos="$transition_pos" --resize="$resize_mode"
-	else
-		feh --bg-fill $file
-	fi
-fi
-
-# generate wal color output
-# The --cols16 flag will not work with the standard pywal package in most repos
-# you will need to build pywal with 16 color pallet support yourself
-# or from the AUR pkg pywal-16-colors on ArchLinux
-wal --cols16 -i $file -s -n -q
-
-# reload window manager
-if [ "$XDG_SESSION_DESKTOP" = "Hyprland" ]; then
-	hyprctl reload -q
-elif [ "$XDG_SESSION_DESKTOP" = "river" ]; then
-	/usr/bin/env bash $HOME/.config/river/conf/theme
-fi
+$script "$img_path"
